### ISSUE TITLE
Color theme

### ISSUE THREAD

**Issue by Monal5031** [Monal5031/WebsiteProject-IntroToIT#1]
Please decide the color theme of the website.
We will make it consistent throughout.

**Comment by Anshuman-Verma** [comment]
Colors will be updated in a while, meanwhile work can be initiated over the html content so we directly apply the css over them all.

**Comment by Anshuman-Verma** [comment]
Let's keep the color theme as white.
However the navbar will have the following scheme (which i will take care of) :
-Current Window: #2d8659
- Navbar Windows:  #666666
- Hovered Option : #000000

**Comment by Monal5031** [comment]
@Anshuman-Verma Please add a new contributing.md file wherein mention these color codes to used throughout.
