### ISSUE TITLE
Work Division

### ISSUE THREAD

**Issue by Anshuman-Verma** [Monal5031/WebsiteProject-IntroToIT#2]
Anshuman:
-Home Page
-Contacts

Monal:
-Sports Section
-About Committe

Test a lot of stuff and push the ones u feel are appropriate or which makes the website look well.

**Comment by Monal5031** [comment]
@Anshuman-Verma 
Don't directly push over the master, make a separate branch then send a PR

**Comment by Monal5031** [comment]
$.getJSON("http://www.lgtm.in/g", function (data) {
          $("textarea[name='comment[body]']").
             append("\n\n" + data.markdown);
        });
